#
#   API for SmartMeals
#

openapi: "3.0.3"

info: 
  description: backend
  version: 0.1.0
  title: SmartMeals

servers:
  - url: http://localhost:3010/v0

paths:
  /test:
    get:
      description: Test Endpoint
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'