const ingredientCategories = {
    "Protein": [
      "chicken",
      "beef",
      "pork",
      "fish",
      "tofu",
      "tempeh",
      "beans",
      "lentils",
      "eggs",
      "chicken breast",
      "burger patty",
      "eggs",
      "pancetta",
      "beef sirloin",
      "ground bork",
      "ground beef",
      "salmon fillet",
      "shrimp",
      "skinless chicken breast halves",
      "pepperoni"
    ],
    "Grains": [
      "rice",
      "quinoa",
      "oats",
      "barley",
      "corn",
      "wheat",
      "bread",
      "pasta",
      "couscous",
      "bulgur",
      "farro",
      "spaghetti"
    ],
    "Vegetables": [
      "broccoli",
      "carrots",
      "spinach",
      "kale",
      "lettuce",
      "tomatoes",
      "cherry tomatoes",
      "cucumber",
      "peppers",
      "onions",
      "garlic",
      "potatoes",
      "sweet potatoes",
      "squash",
      "zucchini",
      "asparagus",
      "green beans",
      "peas",
      "corn",
      "mushrooms",
      "baby bella mushrooms",
      "jalepeno",
      "carrot",
      "bell pepper",
      "red bell pepper",
      "garlic",
      "red onion",
      "onion",
      "kalamata olives",
      "ginger",
      "pickles",
      "eggplant",
      "yellow squash",
      "peas",
      "corn"
    ],
    "Dairy": [
      "milk",
      "cheese",
      "yogurt",
      "butter",
      "cream",
      "sour cream",
      "cream cheese",
      "parmesan",
      "american cheddar cheese",
      "parmesan cheese",
      "feta cheese",
      "mozzarella cheese"
    ],
    "Oils": [
      "olive oil",
      "canola oil",
      "coconut oil",
      "vegetable oil",
      "avocado oil",
      "sesame oil"
    ],
    "Fruit": [
      "apples",
      "bananas",
      "oranges",
      "grapefruit",
      "grapes",
      "berries",
      "kiwi",
      "mango",
      "pineapple",
      "peaches",
      "nectarines",
      "plums",
      "cherries",
      "lemons",
      "limes",
      "avocado",
      "pineapple"
    ],
    "Nuts and seeds": [
      "almonds",
      "walnuts",
      "pecans",
      "cashews",
      "peanuts",
      "pistachios",
      "sunflower seeds",
      "pumpkin seeds",
      "chia seeds",
      "flax seeds",
      "sesame seeds",
      "pine nuts"
    ]
};
module.exports = {ingredientCategories};